package app;

import org.apache.causeway.applib.annotation.DomainService;

import customers.Customer;
import customers.Product;

/**
 * Hand-written domain service. Represents the "coexisting" code that is NOT
 * generated by the DSL. The generated {@link Customer} entity's action body
 * calls into this service, and this service references the generated entities —
 * bidirectional plain-Java references on one shared classpath.
 */
@DomainService
public class OrderService {

    public void placeOrder(final Customer customer, final Product product, final int quantity) {
        // hand-written business logic would live here
    }
}
